In [14]:
from dotenv import load_dotenv, find_dotenv
_ = load_dotenv(find_dotenv())

In [26]:
import qianfan

def gen_wenxin_messages(prompt):
    '''
    构造模型请求参数 messages

    请求参数：
        prompt: 对应的用户提示词
    '''
    messages = [{"role": "user", "content": prompt}]
    return messages


def get_completion(prompt, model="ERNIE-Bot", temperature=0.01):
    '''
    获取模型调用结果

    请求参数：
        prompt: 对应的提示词
        model: 调用的模型，默认为 ERNIE-Bot，也可以按需选择 ERNIE-Bot-4 等其他模型
        temperature: 模型输出的温度系数，控制输出的随机程度，取值范围是 0~1.0，且不能设置为 0。温度系数越低，输出内容越一致。
    '''

    chat_comp = qianfan.ChatCompletion()
    message = gen_wenxin_messages(prompt)

    resp = chat_comp.do(messages=message, 
                        model=model,
                        temperature = temperature,
                        system="你是一名异常话单分析员.你已经使用一些机器学习方法分析了数据，主要发现：1. PE12的错误原因是：“特殊通话类型为 ['8163','8169']and 通话时长<60”，而特殊通话类型 主要由对方电话号码的后三位 和 总免费额度为vpmn来区分。如果对方电话号码后三位是163且是vpmn，则为8163；对方电话号码后三位是169且是vpmn，则为8169；如果对方电话号码不是163也不是169也不是vpmn，则特殊通话类型为901JJJ。  2. 如果是RN78错误原因，其直接原因是动态漫游号 match ['13900','8613900','1374','861374','1344','861344']，但因为这个错误类型的数据没有动态漫游号及对方电话号码特征。通过使用随机森林模型建模，区分RN78及PE12，发现RN78类错误，主要影响的特征是漫游费用和长途通话费用不为0，电话号码的访问地和归属地不同，且通话时长分布范围更广，相比PE12通话时间更长，对方电话归属地比较分散。")

    return resp["result"]


In [28]:
get_completion(
               
               '''
为了生成一份准确的错误原因分析报告，请遵循以下步骤和指导原则来分析和撰写报告。

一、数据准备与理解

审查数据字段：首先，仔细阅读并分析提供的错误数据记录中的所有字段，特别是与错误直接相关的字段（如ERRORCODE, 电话号码, 对方电话号码_后三位, 总免费额度, 通话时长, 特殊通话类型等）。
数据验证：确认数据的准确性和完整性，特别是那些用于错误判定的关键字段。
二、错误判定规则回顾

了解错误代码：明确ERRORCODE所代表的错误类型及其通常的触发条件。
复习判定规则：回顾与错误代码相关的判定规则。例如，对于PE12错误，需要知道其判定条件为“特殊通话类型为 ['8163','8169'] 且通话时长<60秒”。而特殊通话类型 主要由对方电话号码的后三位 和 总免费额度为vpmn来区分。如果对方电话号码后三位是163且是vpmn，则为8163；对方电话号码后三位是169且是vpmn，则为8169；如果对方电话号码不是163也不是169也不是vpmn，则特殊通话类型为901JJJ。  2. 如果是RN78错误原因，其直接原因是动态漫游号 match ['13900','8613900','1374','861374','1344','861344']，但因为这个错误类型的数据没有动态漫游号及对方电话号码特征。通过使用随机森林模型建模，区分RN78及PE12，发现RN78类错误，主要影响的特征是漫游费用和长途通话费用不为0，电话号码的访问地和归属地不同，且通话时长分布范围更广，相比PE12通话时间更长，对方电话归属地比较分散。
三、错误原因分析

匹配判定条件：将错误数据中的字段值与错误判定规则进行匹配，确定哪些条件被满足，哪些可能未被满足或需要额外注意。
逻辑分析：使用逻辑推理，结合数据的实际值和判定规则，分析为何这些条件会触发错误。例如，检查特殊通话类型是如何根据对方电话号码后三位和总免费额度确定的，以及通话时长是否确实小于60秒。
排除法：如果数据中存在多个可能影响错误判定的因素，使用排除法来确定哪个或哪些因素是导致错误的关键原因。
四、综合判断与结论

总结原因：基于上述分析，总结导致该错误的具体原因。
明确错误类型：根据分析结果，明确指出错误类型及其特征。
五、建议与改进措施

提出改进建议：基于错误原因，提出针对性的改进建议，以减少或避免未来类似错误的发生。这可能涉及系统逻辑的优化、数据处理流程的改进、监控和预警机制的增强等方面。
实施建议的可行性：简要评估所提建议的实施难度和可行性，为决策者提供参考。
六、报告撰写

结构清晰：按照引言、数据概述、错误原因分析、综合判断与建议、结论的顺序撰写报告，确保结构清晰、逻辑连贯。
准确表达：使用准确、专业的语言表达分析结果和建议，避免歧义和模糊。
引用来源：如果报告中引用了外部资料或规则，请注明来源以增加报告的可信度。
请按照上述步骤和指导原则，基于给定的错误数据记录，生成一份详尽且准确的错误原因分析报告。

以下是示例数据：
漫游类型: 0
电话号码: 1510333****
访问地区: 313
归属地区: 313
归属管理费用: 1.311
对方电话号码: 668163
对方电话号码_后三位: 163
对方访问地区: 668
对方归属地区: 668
对方地区管理费用: 2.2
通话开始时间: 2024/7/1 9:23
通话时长: 23
无线电频率功率能力: 0
漫游费用: 0
长途通话费用: 0
ERRORCODE: PE12
特殊通话类型: 8163
总免费额度: vpmn

               '''
               , model="Yi-34B-Chat")


[WARNING][2024-08-29 14:50:37.164] base.py:844 [t:34328]: This key `system` does not seem to be a parameter that the model `Yi-34B-Chat` will accept


"错误原因分析报告\n\n引言\n本报告旨在详细分析一组错误数据记录，以确定错误的具体原因，并提出相应的改进建议。错误数据记录中包含了与错误判定相关的关键字段，如ERRORCODE、电话号码、对方电话号码后三位、总免费额度、通话时长、特殊通话类型等。通过严格的数据验证和逻辑分析，我们将为减少或避免未来类似错误的发生提供准确且可行的建议。\n\n数据概述\n在分析过程中，我们首先对数据字段进行了审查，并确认了数据的准确性和完整性。数据记录中，漫游类型为0，电话号码为1510333****，访问地区为313，归属地区也为313，归属管理费用为1.311，对方电话号码为668163，对方电话号码后三位为163，对方访问地区为668，对方归属地区为668，对方地区管理费用为2.2，通话时长为23分钟，无线电频率功率能力为0，漫游费用为0，长途通话费用为0，ERRORCODE为PE12，特殊通话类型为8163，总免费额度为vpmn。\n\n错误原因分析\n根据提供的错误判定规则，PE12错误的触发条件是“特殊通话类型为 ['8163','8169'] 且通话时长<60秒”。特殊通话类型由对方电话号码的后三位和总免费额度为vpmn来区分。在分析中，我们发现对方电话号码后三位为163，且总免费额度为vpmn，因此特殊通话类型为8163。通话时长为23分钟，小于60秒，符合PE12错误的判定条件。因此，我们可以确定，通话时长过短是导致PE12错误的主要原因。\n\n综合判断与建议\n基于上述分析，我们可以得出结论，PE12错误是由于通话时长小于60秒而触发的。为了减少此类错误的发生，我们建议在未来的数据处理中，增加对通话时长的监控和校正机制。此外，考虑到RN78错误的原因可能与动态漫游号和通话时长有关，我们建议进一步分析通话时长分布和动态漫游号的关联性，以期能够更准确地识别和预防RN78错误。\n\n结论\n综上所述，PE12错误的主要原因是通话时长过短，而RN78错误的原因可能与动态漫游号和通话时长有关。我们建议通过改进数据处理流程和监控机制来减少这些错误的发生。\n\n建议与改进措施\n1. 对于PE12错误，建议在数据处理中设置额外的检查点，确保通话时长记录的准确性。\n2. 对于RN78错误，建议分析动态漫游号与通话时长的关系，并考虑在判定规则中加入相关因素。\n3. 建议

# 错误原因分析报告

## 引言
本报告旨在详细分析一组错误数据记录，以确定错误的具体原因，并提出相应的改进建议。错误数据记录中包含了与错误判定相关的关键字段，如ERRORCODE、电话号码、对方电话号码后三位、总免费额度、通话时长、特殊通话类型等。通过严格的数据验证和逻辑分析，我们将为减少或避免未来类似错误的发生提供准确且可行的建议。

## 数据概述
在分析过程中，我们首先对数据字段进行了审查，并确认了数据的准确性和完整性。数据记录中，漫游类型为0，电话号码为1510333****，访问地区为313，归属地区也为313，归属管理费用为1.311，对方电话号码为668163，对方电话号码后三位为163，对方访问地区为668，对方归属地区为668，对方地区管理费用为2.2，通话时长为23分钟，无线电频率功率能力为0，漫游费用为0，长途通话费用为0，ERRORCODE为PE12，特殊通话类型为8163，总免费额度为vpmn。

## 错误原因分析
根据提供的错误判定规则，PE12错误的触发条件是“特殊通话类型为 ['8163','8169'] 且通话时长<60秒”。特殊通话类型由对方电话号码的后三位和总免费额度为vpmn来区分。在分析中，我们发现对方电话号码后三位为163，且总免费额度为vpmn，因此特殊通话类型为8163。通话时长为23分钟，小于60秒，符合PE12错误的判定条件。因此，我们可以确定，通话时长过短是导致PE12错误的主要原因。

## 综合判断与建议
基于上述分析，我们可以得出结论，PE12错误是由于通话时长小于60秒而触发的。为了减少此类错误的发生，我们建议在未来的数据处理中，增加对通话时长的监控和校正机制。此外，考虑到RN78错误的原因可能与动态漫游号和通话时长有关，我们建议进一步分析通话时长分布和动态漫游号的关联性，以期能够更准确地识别和预防RN78错误。

## 结论
综上所述，PE12错误的主要原因是通话时长过短，而RN78错误的原因可能与动态漫游号和通话时长有关。我们建议通过改进数据处理流程和监控机制来减少这些错误的发生。

## 建议与改进措施
1. 对于PE12错误，建议在数据处理中设置额外的检查点，确保通话时长记录的准确性。
2. 对于RN78错误，建议分析动态漫游号与通话时长的关系，并考虑在判定规则中加入相关因素。
3. 建议定期审查和更新错误判定规则，以确保其与实际业务逻辑保持一致。
4. 建议实施更严格的测试和质量控制措施，以减少错误数据记录的产生。

## 实施建议的可行性
上述建议的实施难度较低，且具有较高的可行性。通过技术手段实现对通话时长的监控和校正，以及动态漫游号的分析，可以有效减少错误的发生。同时，定期审查和更新错误判定规则，以及实施更严格的测试和质量控制措施，都是可以立即执行的改进措施。

## 报告撰写
本报告按照引言、数据概述、错误原因分析、综合判断与建议、结论的顺序撰写，结构清晰，逻辑连贯。所有分析均基于给定的错误数据记录，并引用了相关的判定规则。报告使用准确、专业的语言表达，并提供了明确的改进建议和实施评估。

我们相信，通过实施上述建议，可以显著减少错误数据记录的发生，并提高系统的整体稳定性。